const questions16P = [
  {id: 1,  text: "You enjoy being the center of attention.",            trait: "EI", reverse: false},
  {id: 2,  text: "You feel drained after long social events.",          trait: "EI", reverse: true},
  {id: 3,  text: "You easily start conversations with strangers.",      trait: "EI", reverse: false},
  {id: 4,  text: "You prefer a quiet evening over a lively party.",     trait: "EI", reverse: true},
  {id: 5,  text: "Large groups of people energize you.",                trait: "EI", reverse: false},
  {id: 6,  text: "You often keep your thoughts to yourself.",           trait: "EI", reverse: true},
  {id: 7,  text: "You enjoy group activities and team projects.",       trait: "EI", reverse: false},
  {id: 8,  text: "You need alone time to feel like yourself again.",    trait: "EI", reverse: true},
  {id: 9,  text: "You usually initiate conversations or plans.",        trait: "EI", reverse: false},
  {id: 10, text: "You prefer deep one-on-one talks over group chats.",  trait: "EI", reverse: true},
 
  {id: 11, text: "You enjoy abstract theories over concrete facts.",    trait: "NS", reverse: false},
  {id: 12, text: "You trust hands-on experience over theory.",          trait: "NS", reverse: true},
  {id: 13, text: "You often imagine future 'what if' scenarios.",       trait: "NS", reverse: false},
  {id: 14, text: "You prefer step-by-step instructions over big picture.", trait: "NS", reverse: true},
  {id: 15, text: "You enjoy ideas even with no practical use.",         trait: "NS", reverse: false},
  {id: 16, text: "You focus on specific details over the big picture.", trait: "NS", reverse: true},
  {id: 17, text: "You like unconventional ways of solving problems.",   trait: "NS", reverse: false},
  {id: 18, text: "You prefer proven methods over experimental ones.",   trait: "NS", reverse: true},
  {id: 19, text: "You look for deeper meaning or patterns in events.",  trait: "NS", reverse: false},
  {id: 20, text: "You focus on what is real now, not what could be.",   trait: "NS", reverse: true},
 
  {id: 21, text: "You prioritize logic over emotions when deciding.",   trait: "TF", reverse: false},
  {id: 22, text: "You consider feelings before making any decision.",   trait: "TF", reverse: true},
  {id: 23, text: "You value honesty more than tactfulness.",            trait: "TF", reverse: false},
  {id: 24, text: "You go out of your way to avoid conflict.",           trait: "TF", reverse: true},
  {id: 25, text: "You stay detached and objective in emotional situations.", trait: "TF", reverse: false},
  {id: 26, text: "You are easily moved by stories of hardship.",        trait: "TF", reverse: true},
  {id: 27, text: "You prefer direct, honest criticism over soft feedback.", trait: "TF", reverse: false},
  {id: 28, text: "You often decide based on gut feeling.",              trait: "TF", reverse: true},
  {id: 29, text: "You value fairness over compassion in disputes.",     trait: "TF", reverse: false},
  {id: 30, text: "Making people around you feel valued matters deeply.", trait: "TF", reverse: true},
 
  {id: 31, text: "You prefer having a clear plan before starting.",     trait: "JP", reverse: false},
  {id: 32, text: "You enjoy keeping options open and adapting as you go.", trait: "JP", reverse: true},
  {id: 33, text: "Unexpected plan changes make you uncomfortable.",     trait: "JP", reverse: false},
  {id: 34, text: "You start many projects without finishing old ones.", trait: "JP", reverse: true},
  {id: 35, text: "You like things decided and settled, not open-ended.", trait: "JP", reverse: false},
  {id: 36, text: "You work better under pressure than on a schedule.",  trait: "JP", reverse: true},
  {id: 37, text: "You maintain an organized workspace and routine.",    trait: "JP", reverse: false},
  {id: 38, text: "Strict schedules and rigid routines stress you out.", trait: "JP", reverse: true},
  {id: 39, text: "You finish one task fully before moving to the next.", trait: "JP", reverse: false},
  {id: 40, text: "You enjoy spontaneous decisions and last-minute plans.", trait: "JP", reverse: true},
];
 
const questionsBig5 = [
  {id: 1,  text: "You have a vivid imagination and enjoy creative work.",   trait: "O", reverse: false},
  {id: 2,  text: "You prefer familiar routines over new experiences.",      trait: "O", reverse: true},
  {id: 3,  text: "You enjoy exploring philosophical or abstract ideas.",    trait: "O", reverse: false},
  {id: 4,  text: "Art, music, or literature moves you deeply.",             trait: "O", reverse: false},
  {id: 5,  text: "You stick to what you know rather than trying new things.",trait: "O", reverse: true},
  {id: 6,  text: "You are curious and love learning about different topics.",trait: "O", reverse: false},
  {id: 7,  text: "You rarely daydream or think about fantastical ideas.",   trait: "O", reverse: true},
  {id: 8,  text: "You enjoy experimenting with new ideas and perspectives.",trait: "O", reverse: false},
 
  {id: 9,  text: "You always complete tasks on time.",                        trait: "C", reverse: false},
  {id: 10, text: "You often leave things until the last minute.",             trait: "C", reverse: true},
  {id: 11, text: "You keep your space neat and organized.",                   trait: "C", reverse: false},
  {id: 12, text: "You find it hard to stick to long-term goals.",             trait: "C", reverse: true},
  {id: 13, text: "You pay close attention to detail in everything you do.",   trait: "C", reverse: false},
  {id: 14, text: "You act impulsively without thinking through consequences.", trait: "C", reverse: true},
  {id: 15, text: "You set clear goals and work toward them systematically.",  trait: "C", reverse: false},
  {id: 16, text: "People can always count on you to deliver.",                trait: "C", reverse: false},
 
  {id: 17, text: "You feel confident and comfortable in social situations.",  trait: "E", reverse: false},
  {id: 18, text: "You often feel awkward around new people.",                 trait: "E", reverse: true},
  {id: 19, text: "You enjoy being around people and thrive socially.",        trait: "E", reverse: false},
  {id: 20, text: "You tend to be quiet and reserved in most situations.",     trait: "E", reverse: true},
  {id: 21, text: "You are enthusiastic and expressive with others.",          trait: "E", reverse: false},
  {id: 22, text: "You prefer working alone over working in a group.",         trait: "E", reverse: true},
  {id: 23, text: "You find it easy to make friends and meet new people.",     trait: "E", reverse: false},
  {id: 24, text: "You have a lot of energy and always have something going.", trait: "E", reverse: false},
 
  {id: 25, text: "You are considerate and kind to almost everyone.",          trait: "A", reverse: false},
  {id: 26, text: "You easily trust and believe in the goodness of others.",   trait: "A", reverse: false},
  {id: 27, text: "You often challenge or argue when you disagree.",           trait: "A", reverse: true},
  {id: 28, text: "You prefer cooperating over competing with others.",        trait: "A", reverse: false},
  {id: 29, text: "You can be cold and unconcerned about others' feelings.",   trait: "A", reverse: true},
  {id: 30, text: "You compromise your own needs for the sake of others.",     trait: "A", reverse: false},
  {id: 31, text: "You tend to be critical and find faults in people easily.", trait: "A", reverse: true},
  {id: 32, text: "You feel deep empathy for people going through hard times.", trait: "A", reverse: false},
 
  {id: 33, text: "You frequently feel anxious without a clear reason.",       trait: "N", reverse: false},
  {id: 34, text: "You remain calm and composed under pressure.",              trait: "N", reverse: true},
  {id: 35, text: "Your mood changes frequently throughout the day.",          trait: "N", reverse: false},
  {id: 36, text: "You rarely feel sad or emotionally down.",                  trait: "N", reverse: true},
  {id: 37, text: "You overthink and imagine worst-case scenarios.",           trait: "N", reverse: false},
  {id: 38, text: "You recover quickly after setbacks or disappointments.",    trait: "N", reverse: true},
  {id: 39, text: "You feel easily overwhelmed when things go wrong.",         trait: "N", reverse: false},
  {id: 40, text: "You are generally at peace and satisfied with your life.",  trait: "N", reverse: true},
];